export const SET_HENDELSER = 'SET_HENDELSER';
export const APNE_HENDELSER = 'ÅPNE_HENDELSER';
export const LEGG_TIL_HENDELSER = 'LEGG_TIL_HENDELSER';
export const SET_HENDELSEDATA = 'SET_HENDELSEDATA';

export const HENTER_LEDETEKSTER = 'HENTER_LEDETEKSTER';
export const LEDETEKSTER_HENTET = 'LEDETEKSTER_HENTET';
export const HENT_LEDETEKSTER_FEILET = 'HENT_LEDETEKSTER_FEILET';
export const HENT_LEDETEKSTER_FORESPURT = 'HENT_LEDETEKSTER_FORESPURT';

export const HENT_TIDSLINJER_FEILET = 'HENT_TIDSLINJER_FEILET';
export const HENTER_TIDSLINJER = 'HENTER_TIDSLINJER';
export const SET_TIDSLINJER = 'SET_TIDSLINJER';
export const HENT_TIDSLINJER_FORESPURT = 'HENT_TIDSLINJER_FORESPURT';
export const HENT_TIDSLINJER_IKKE_TILGANG = 'HENT_TIDSLINJER_IKKE_TILGANG';

export const BRUKER_ER_UTLOGGET = 'BRUKER_ER_UTLOGGET';
